[theme]
base="light"
backgroundColor="white"
secondaryBackgroundColor="lavender"
codeBackgroundColor="powderBlue"
textColor="#1c1917"
codeTextColor="#1c1917"

[theme.sidebar]
backgroundColor="ghostWhite"
secondaryBackgroundColor="lavender"
